export const hospitals = [
  {
    id: 1,
    name: "Nairobi General Hospital",
    location: "Nairobi Central",
    specialties: ["Cardiology", "Orthopedics", "Pediatrics"],
    rating: 4.5,
    doctors: [
      { id: 1, name: "Dr. Sarah Johnson", specialty: "Cardiology" },
      { id: 2, name: "Dr. Michael Chen", specialty: "Orthopedics" },
      { id: 3, name: "Dr. Emily Davis", specialty: "Pediatrics" },
    ],
    facilities: ["Emergency Care", "ICU", "Surgery", "Pharmacy"],
    verified: true,
  },
  {
    id: 2,
    name: "Kenya Medical Center",
    location: "Westlands",
    specialties: ["Dermatology", "Neurology", "Dentistry"],
    rating: 4.8,
    doctors: [
      { id: 4, name: "Dr. David Mwangi", specialty: "Neurology" },
      { id: 5, name: "Dr. Lisa Wong", specialty: "Dermatology" },
      { id: 6, name: "Dr. Kevin Patel", specialty: "Dentistry" },
    ],
    facilities: ["Laboratory", "Radiology", "Pharmacy"],
    verified: true,
  },
  {
    id: 3,
    name: "Mombasa Community Hospital",
    location: "Mombasa",
    specialties: ["General Medicine", "Gynecology", "Pediatrics"],
    rating: 4.2,
    doctors: [
      { id: 7, name: "Dr. John Kamau", specialty: "General Medicine" },
      { id: 8, name: "Dr. Anne Ochieng", specialty: "Gynecology" },
      { id: 9, name: "Dr. Peter Otieno", specialty: "Pediatrics" },
    ],
    facilities: ["Emergency Care", "Maternity", "Pediatric Ward"],
    verified: true,
  },
  {
    id: 4,
    name: "Eldoret Medical Plaza",
    location: "Eldoret",
    specialties: ["Oncology", "Radiology", "Nephrology"],
    rating: 4.6,
    doctors: [
      { id: 10, name: "Dr. Susan Njeri", specialty: "Oncology" },
      { id: 11, name: "Dr. Charles Karanja", specialty: "Radiology" },
    ],
    facilities: ["Chemotherapy", "Dialysis", "Radiation Therapy"],
    verified: true,
  },
  {
    id: 5,
    name: "Kisumu Heart Institute",
    location: "Kisumu",
    specialties: ["Cardiology", "Pulmonology"],
    rating: 4.7,
    doctors: [
      { id: 12, name: "Dr. Grace Wambui", specialty: "Cardiology" },
      { id: 13, name: "Dr. Mark Omondi", specialty: "Pulmonology" },
    ],
    facilities: ["ICU", "Cardiac Surgery", "Pulmonary Rehab"],
    verified: true,
  },
  {
    id: 6,
    name: "Machakos Wellness Center",
    location: "Machakos",
    specialties: ["Psychiatry", "Nutrition", "Physical Therapy"],
    rating: 4.3,
    doctors: [
      { id: 14, name: "Dr. Mary Njenga", specialty: "Psychiatry" },
      { id: 15, name: "Dr. Joseph Kiplagat", specialty: "Nutrition" },
    ],
    facilities: ["Counseling", "Dietary Consultations", "Rehabilitation"],
    verified: true,
  },
  {
    id: 7,
    name: "Nakuru Health Services",
    location: "Nakuru",
    specialties: ["Gastroenterology", "Endocrinology"],
    rating: 4.4,
    doctors: [
      { id: 16, name: "Dr. Lawrence Otieno", specialty: "Gastroenterology" },
      { id: 17, name: "Dr. Jane Mutua", specialty: "Endocrinology" },
    ],
    facilities: ["Endoscopy", "Diabetes Clinic", "Nutrition Center"],
    verified: true,
  },
  {
    id: 8,
    name: "Thika Family Clinic",
    location: "Thika",
    specialties: ["Family Medicine", "Pediatrics"],
    rating: 4.5,
    doctors: [
      { id: 18, name: "Dr. Alice Mwende", specialty: "Family Medicine" },
      { id: 19, name: "Dr. Brian Ndungu", specialty: "Pediatrics" },
    ],
    facilities: ["Vaccination", "Wellness Checks", "Emergency Care"],
    verified: true,
  },
  {
    id: 9,
    name: "Kitale Specialist Hospital",
    location: "Kitale",
    specialties: ["Urology", "Geriatrics"],
    rating: 4.3,
    doctors: [
      { id: 20, name: "Dr. Rose Kinyua", specialty: "Urology" },
      { id: 21, name: "Dr. Alex Muli", specialty: "Geriatrics" },
    ],
    facilities: ["Surgery", "Physiotherapy", "Pharmacy"],
    verified: true,
  },
  {
    id: 10,
    name: "Nyeri County Hospital",
    location: "Nyeri",
    specialties: ["Ophthalmology", "ENT", "Dermatology"],
    rating: 4.6,
    doctors: [
      { id: 22, name: "Dr. Francis Kimani", specialty: "Ophthalmology" },
      { id: 23, name: "Dr. Jane Njoroge", specialty: "ENT" },
      { id: 24, name: "Dr. Samuel Ngugi", specialty: "Dermatology" },
    ],
    facilities: ["Eye Clinic", "Hearing Tests", "Skin Care"],
    verified: true,
  },
  {
    id: 11,
    name: "Kericho Green Hospital",
    location: "Kericho",
    specialties: ["Neonatology", "Gynecology"],
    rating: 4.7,
    doctors: [
      { id: 25, name: "Dr. Sarah Wanjiku", specialty: "Neonatology" },
      { id: 26, name: "Dr. James Mwangi", specialty: "Gynecology" },
    ],
    facilities: ["NICU", "Maternity Ward", "Pediatric Surgery"],
    verified: true,
  },
  {
    id: 12,
    name: "Meru District Hospital",
    location: "Meru",
    specialties: ["Hematology", "Pathology"],
    rating: 4.5,
    doctors: [
      { id: 27, name: "Dr. Lucy Muthoni", specialty: "Hematology" },
      { id: 28, name: "Dr. Daniel Kuria", specialty: "Pathology" },
    ],
    facilities: ["Blood Bank", "Lab Services", "Oncology"],
    verified: true,
  },
  {
    id: 13,
    name: "Nairobi West Hospital",
    location: "Nairobi West",
    specialties: ["Cardiology", "Orthopedics", "Pediatrics"],
    rating: 4.6,
    doctors: [
      { id: 29, name: "Dr. Naomi Karani", specialty: "Cardiology" },
      { id: 30, name: "Dr. Victor Kamau", specialty: "Orthopedics" },
      { id: 31, name: "Dr. Linda Mburu", specialty: "Pediatrics" },
    ],
    facilities: ["ICU", "Emergency", "Surgery", "Radiology"],
    verified: true,
  },
  {
    id: 14,
    name: "Eldoret Referral Hospital",
    location: "Eldoret",
    specialties: ["Neurosurgery", "Orthopedics", "Plastic Surgery"],
    rating: 4.4,
    doctors: [
      { id: 32, name: "Dr. Henry Kiplagat", specialty: "Neurosurgery" },
      { id: 33, name: "Dr. Elizabeth Kiptoo", specialty: "Plastic Surgery" },
    ],
    facilities: ["Neuro ICU", "Orthopedic Surgery", "Plastic Surgery"],
    verified: true,
  },
  {
    id: 15,
    name: "Kisii Teaching and Referral Hospital",
    location: "Kisii",
    specialties: ["ENT", "Pediatrics", "Cardiology"],
    rating: 4.5,
    doctors: [
      { id: 34, name: "Dr. Mary Atieno", specialty: "ENT" },
      { id: 35, name: "Dr. Thomas Obiero", specialty: "Cardiology" },
    ],
    facilities: ["ICU", "Emergency", "Surgery", "Radiology"],
    verified: true,
  },
  {
    id: 16,
    name: "Machakos Level 5 Hospital",
    location: "Machakos",
    specialties: ["Neurosurgery", "Orthopedics", "Plastic Surgery"],
    rating: 4.4,
    doctors: [
      { id: 36, name: "Dr. Henry Kiplagat", specialty: "Neurosurgery" },
      { id: 37, name: "Dr. Elizabeth Kiptoo", specialty: "Plastic Surgery" },
    ],
    facilities: ["Neuro ICU", "Orthopedic Surgery", "Plastic Surgery"],
    verified: true,
  },
  {
    id: 17,
    name: "Nyeri County Hospital",
    location: "Nyeri",
    specialties: ["Ophthalmology", "ENT", "Dermatology"],
    rating: 4.6,
    doctors: [
      { id: 38, name: "Dr. Francis Kimani", specialty: "Ophthalmology" },
      { id: 39, name: "Dr. Jane Njoroge", specialty: "ENT" },
      { id: 40, name: "Dr. Samuel Ngugi", specialty: "Dermatology" },
    ],
    facilities: ["Eye Clinic", "Hearing Tests", "Skin Care"],
    verified: true,
  },
  {
    id: 18,
    name: "Kericho Green Hospital",
    location: "Kericho",
    specialties: ["Neonatology", "Gynecology"],
    rating: 4.7,
    doctors: [
      { id: 41, name: "Dr. Sarah Wanjiku", specialty: "Neonatology" },
      { id: 42, name: "Dr. James Mwangi", specialty: "Gynecology" },
    ],
    facilities: ["NICU", "Maternity Ward", "Pediatric Surgery"],
    verified: true,
  },
  {
    id: 19,
    name: "Meru District Hospital",
    location: "Meru",
    specialties: ["Hematology", "Pathology"],
    rating: 4.5,
    doctors: [
      { id: 43, name: "Dr. Lucy Muthoni", specialty: "Hematology" },
      { id: 44, name: "Dr. Daniel Kuria", specialty: "Pathology" },
    ],
    facilities: ["Blood Bank", "Lab Services", "Oncology"],
    verified: true,
  },
  {
    id: 20,
    name: "Thika Level 5 Hospital",
    location: "Thika",
    specialties: ["Gastroenterology", "Endocrinology", "Ophthalmology"],
    rating: 4.5,
    doctors: [
      { id: 45, name: "Dr. Lawrence Otieno", specialty: "Gastroenterology" },
      { id: 46, name: "Dr. Jane Mutua", specialty: "Endocrinology" },
      { id: 47, name: "Dr. Francis Kimani", specialty: "Ophthalmology" },
    ],
    facilities: ["Endoscopy", "Diabetes Clinic", "Eye Clinic"],
    verified: true,
  },
  {
    id: 21,
    name: "Kisumu Level 6 Hospital",
    location: "Kisumu",
    specialties: ["Cardiology", "Neurology", "Orthopedics"],
    rating: 4.6,
    doctors: [
      { id: 48, name: "Dr. John Omondi", specialty: "Cardiology" },
      { id: 49, name: "Dr. Alice Achieng", specialty: "Neurology" },
      { id: 50, name: "Dr. Michael Kiptoo", specialty: "Orthopedics" },
    ],
    facilities: ["ICU", "Emergency", "Radiology"],
    verified: true,
  },
  {
    id: 22,
    name: "Mombasa Level 5 Hospital",
    location: "Mombasa",
    specialties: ["Pediatrics", "Gynecology", "Cardiology"],
    rating: 4.6,
    doctors: [
      { id: 51, name: "Dr. John Kamau", specialty: "Pediatrics" },
      { id: 52, name: "Dr. Anne Ochieng", specialty: "Gynecology" },
      { id: 53, name: "Dr. Sarah Johnson", specialty: "Cardiology" },
    ],
    facilities: ["Emergency Care", "ICU", "Surgery"],
    verified: true,
  },
  {
    id: 23,
    name: "Nairobi East Hospital",
    location: "Nairobi East",
    specialties: ["Nephrology", "Oncology", "Psychiatry"],
    rating: 4.7,
    doctors: [
      { id: 54, name: "Dr. Susan Njeri", specialty: "Nephrology" },
      { id: 55, name: "Dr. Charles Karanja", specialty: "Oncology" },
      { id: 56, name: "Dr. Mary Njenga", specialty: "Psychiatry" },
    ],
    facilities: ["Dialysis", "Chemotherapy", "Counseling"],
    verified: true,
  },
  {
    id: 24,
    name: "Garissa General Hospital",
    location: "Garissa",
    specialties: ["Pediatrics", "Surgery", "Orthopedics"],
    rating: 4.2,
    doctors: [
      { id: 57, name: "Dr. Peter Njoroge", specialty: "Pediatrics" },
      { id: 58, name: "Dr. Alice Mwende", specialty: "Surgery" },
      { id: 59, name: "Dr. Brian Ndungu", specialty: "Orthopedics" },
    ],
    facilities: ["ICU", "Emergency", "Surgery"],
    verified: true,
  },
  {
    id: 25,
    name: "Eldoret Level 6 Hospital",
    location: "Eldoret",
    specialties: ["Neurology", "Orthopedics", "Cardiology"],
    rating: 4.6,
    doctors: [
      { id: 60, name: "Dr. Kevin Patel", specialty: "Neurology" },
      { id: 61, name: "Dr. Joseph Kiplagat", specialty: "Orthopedics" },
      { id: 62, name: "Dr. Victor Kamau", specialty: "Cardiology" },
    ],
    facilities: ["Neuro ICU", "Orthopedic Surgery", "Cardiac Surgery"],
    verified: true,
  },
  {
    id: 26,
    name: "Isiolo General Hospital",
    location: "Isiolo",
    specialties: ["General Medicine", "Dermatology", "Gynecology"],
    rating: 4.3,
    doctors: [
      { id: 63, name: "Dr. Ann Mwangi", specialty: "General Medicine" },
      { id: 64, name: "Dr. Janet Njoroge", specialty: "Dermatology" },
      { id: 65, name: "Dr. Peter Ochieng", specialty: "Gynecology" },
    ],
    facilities: ["Emergency Care", "Maternity", "Dermatology Clinic"],
    verified: true,
  },
  {
    id: 27,
    name: "Nairobi South Hospital",
    location: "Nairobi South",
    specialties: ["Pediatrics", "ENT", "Orthopedics"],
    rating: 4.4,
    doctors: [
      { id: 66, name: "Dr. Sarah Johnson", specialty: "Pediatrics" },
      { id: 67, name: "Dr. Michael Chen", specialty: "ENT" },
      { id: 68, name: "Dr. Emily Davis", specialty: "Orthopedics" },
    ],
    facilities: ["Emergency Care", "ICU", "Surgery"],
    verified: true,
  },
  {
    id: 28,
    name: "Thika Regional Hospital",
    location: "Thika",
    specialties: ["Cardiology", "Neurology", "Endocrinology"],
    rating: 4.5,
    doctors: [
      { id: 69, name: "Dr. David Mwangi", specialty: "Neurology" },
      { id: 70, name: "Dr. Lisa Wong", specialty: "Endocrinology" },
      { id: 71, name: "Dr. Kevin Patel", specialty: "Cardiology" },
    ],
    facilities: ["ICU", "Emergency", "Diabetes Clinic"],
    verified: true,
  },
  {
    id: 29,
    name: "Narok District Hospital",
    location: "Narok",
    specialties: ["General Medicine", "Gynecology", "Pediatrics"],
    rating: 4.2,
    doctors: [
      { id: 72, name: "Dr. George Muli", specialty: "General Medicine" },
      { id: 73, name: "Dr. Anna Wambui", specialty: "Gynecology" },
      { id: 74, name: "Dr. Robert Muthui", specialty: "Pediatrics" },
    ],
    facilities: ["Emergency Care", "Maternity Ward", "Pediatric Unit"],
    verified: true,
  },
  {
    id: 30,
    name: "Busia County Referral Hospital",
    location: "Busia",
    specialties: ["Infectious Diseases", "Pediatrics", "Cardiology"],
    rating: 4.3,
    doctors: [
      { id: 75, name: "Dr. Patrick Olang", specialty: "Infectious Diseases" },
      { id: 76, name: "Dr. Eva Otieno", specialty: "Pediatrics" },
      { id: 77, name: "Dr. Martin Njoroge", specialty: "Cardiology" },
    ],
    facilities: ["Isolation Ward", "ICU", "Emergency"],
    verified: true,
  },
  {
    id: 31,
    name: "Voi County Hospital",
    location: "Voi",
    specialties: ["Dermatology", "Neurology", "Orthopedics"],
    rating: 4.1,
    doctors: [
      { id: 78, name: "Dr. Sharon Kiplangat", specialty: "Dermatology" },
      { id: 79, name: "Dr. Moses Kamotho", specialty: "Neurology" },
      { id: 80, name: "Dr. Joyce Atieno", specialty: "Orthopedics" },
    ],
    facilities: ["Dermatology Clinic", "Neuro Ward", "Ortho Surgery"],
    verified: true,
  },
  {
    id: 32,
    name: "Embu General Hospital",
    location: "Embu",
    specialties: ["General Medicine", "Gynecology", "Pediatrics"],
    rating: 4.0,
    doctors: [
      { id: 81, name: "Dr. Mary Mutua", specialty: "General Medicine" },
      { id: 82, name: "Dr. Janet Wairimu", specialty: "Gynecology" },
      { id: 83, name: "Dr. Andrew Mwangi", specialty: "Pediatrics" },
    ],
    facilities: ["Maternity Ward", "Pediatrics Unit", "Emergency Care"],
    verified: true,
  },
  {
    id: 33,
    name: "Nanyuki Cottage Hospital",
    location: "Nanyuki",
    specialties: ["General Surgery", "Pediatrics", "Orthopedics"],
    rating: 4.5,
    doctors: [
      { id: 84, name: "Dr. Martha Kibor", specialty: "General Surgery" },
      { id: 85, name: "Dr. James Kariuki", specialty: "Pediatrics" },
      { id: 86, name: "Dr. Victor Ochieng", specialty: "Orthopedics" },
    ],
    facilities: ["Surgery", "Pediatric Surgery", "Orthopedic Care"],
    verified: true,
  },
  {
    id: 34,
    name: "Siaya County Hospital",
    location: "Siaya",
    specialties: ["Cardiology", "Nephrology", "Radiology"],
    rating: 4.4,
    doctors: [
      { id: 87, name: "Dr. Faith Wanja", specialty: "Cardiology" },
      { id: 88, name: "Dr. Samuel Kipkorir", specialty: "Nephrology" },
      { id: 89, name: "Dr. Edwin Achieng", specialty: "Radiology" },
    ],
    facilities: ["Cardiac Unit", "Dialysis Center", "Radiology"],
    verified: true,
  },
  {
    id: 35,
    name: "Nyahururu County Hospital",
    location: "Nyahururu",
    specialties: ["General Medicine", "Pediatrics", "Gynecology"],
    rating: 4.1,
    doctors: [
      { id: 90, name: "Dr. Diana Kinyua", specialty: "General Medicine" },
      { id: 91, name: "Dr. Lillian Mwiti", specialty: "Pediatrics" },
      { id: 92, name: "Dr. Timothy Waweru", specialty: "Gynecology" },
    ],
    facilities: ["Maternity Ward", "Pediatrics Unit", "Emergency Care"],
    verified: true,
  },
  {
    id: 36,
    name: "Bungoma County Hospital",
    location: "Bungoma",
    specialties: ["Pediatrics", "Dermatology", "Orthopedics"],
    rating: 4.3,
    doctors: [
      { id: 93, name: "Dr. Millicent Mutua", specialty: "Pediatrics" },
      { id: 94, name: "Dr. Stephen Otieno", specialty: "Dermatology" },
      { id: 95, name: "Dr. Grace Ochieng", specialty: "Orthopedics" },
    ],
    facilities: ["Dermatology Clinic", "Pediatric Care", "Ortho Surgery"],
    verified: true,
  },
  {
    id: 37,
    name: "Kakamega County Referral Hospital",
    location: "Kakamega",
    specialties: ["Infectious Diseases", "Pediatrics", "Cardiology"],
    rating: 4.4,
    doctors: [
      { id: 96, name: "Dr. Irene Makori", specialty: "Infectious Diseases" },
      { id: 97, name: "Dr. Kevin Nyaga", specialty: "Pediatrics" },
      { id: 98, name: "Dr. Benson Musyoka", specialty: "Cardiology" },
    ],
    facilities: ["Isolation Ward", "ICU", "Emergency"],
    verified: true,
  },
  {
    id: 38,
    name: "Kajiado County Hospital",
    location: "Kajiado",
    specialties: ["Nephrology", "Oncology", "Orthopedics"],
    rating: 4.5,
    doctors: [
      { id: 99, name: "Dr. Jackson Karanja", specialty: "Nephrology" },
      { id: 100, name: "Dr. Nancy Njiru", specialty: "Oncology" },
      { id: 101, name: "Dr. John Kamau", specialty: "Orthopedics" },
    ],
    facilities: ["Dialysis Center", "Cancer Treatment", "Ortho Surgery"],
    verified: true,
  },
  {
    id: 39,
    name: "Marsabit County Hospital",
    location: "Marsabit",
    specialties: ["General Surgery", "Pediatrics", "Gynecology"],
    rating: 4.2,
    doctors: [
      { id: 102, name: "Dr. Catherine Nyambura", specialty: "General Surgery" },
      { id: 103, name: "Dr. Eliud Muriuki", specialty: "Pediatrics" },
      { id: 104, name: "Dr. Mary Wanjiku", specialty: "Gynecology" },
    ],
    facilities: ["Surgery", "Maternity Ward", "Pediatric Surgery"],
    verified: true,
  },
  {
    id: 40,
    name: "Laikipia County Hospital",
    location: "Nanyuki",
    specialties: ["General Medicine", "Orthopedics", "Pediatrics"],
    rating: 4.3,
    doctors: [
      { id: 105, name: "Dr. Faith Kendi", specialty: "General Medicine" },
      { id: 106, name: "Dr. Lucas Njoroge", specialty: "Orthopedics" },
      { id: 107, name: "Dr. Mercy Kamau", specialty: "Pediatrics" },
    ],
    facilities: ["Emergency Care", "Ortho Surgery", "Pediatric Unit"],
    verified: true,
  },
];

// Available time slots (9 AM to 5 PM, 30-minute intervals)
export const generateTimeSlots = () => {
  const slots = [];
  const time = new Date();
  time.setHours(9, 0, 0); // Start at 9 AM

  while (time.getHours() < 17) {
    // Until 5 PM
    slots.push(
      time.toLocaleTimeString("en-US", {
        hour: "numeric",
        minute: "2-digit",
        hour12: true,
      }),
    );
    time.setMinutes(time.getMinutes() + 30);
  }

  return slots;
};
